disabled_rules: # rule identifiers to exclude from running
  #- colon
  - conditional_binding_cascade
  #- comma
  - control_statement
  - force_cast
  - legacy_constant
  - legacy_constructor
  - line_length
  - nesting
  - todo
  - trailing_whitespace
  - type_name
  - variable_name
  - cyclomatic_complexity
  - unused_closure_parameter

opt_in_rules: # some rules are only opt-in
  #- empty_count
  #- missing_docs

  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - GithubList

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# These properties are marked as error by default.
force_try: warning

file_length:
  warning: 600
  error: 1200
  
function_body_length:
  warning: 150
  error: 200
  
type_body_length:
  warning: 350
  error: 1000
  
function_parameter_count:
  warning: 10
  error: 15

line_length:
  warning: 150
  error: 250

large_tuple:
  warning: 4
  error: 5

